Guest.create(:id => 1, :name => "Bradley Cooper")
Guest.create(:id => 2, :name => "Robert Klein")
Guest.create(:id => 3, :name => "Soundgarden")
Guest.create(:id => 4, :name => "Lea Michele")
Guest.create(:id => 5, :name => "Nev Schulman")
Guest.create(:id => 6, :name => "Toby Keith")
Guest.create(:id => 7, :name => "Jessica Lange")
Guest.create(:id => 8, :name => "Adam Pally")
Guest.create(:id => 9, :name => "Game featuring Tyga & Wiz Khalifa")
Guest.create(:id => 10, :name => "Nikki Reed")
Guest.create(:id => 11, :name => "Dave Attell")
Guest.create(:id => 12, :name => "Chelsea Handler")
Guest.create(:id => 13, :name => "Charlie Cox")
Guest.create(:id => 14, :name => "Meek Mill")
Guest.create(:id => 15, :name => "Dakota Meyer")
Guest.create(:id => 16, :name => "Lauren Greenfield")
Guest.create(:id => 17, :name => "the Walkmen")
Guest.create(:id => 18, :name => "Thomas Ricks")
Guest.create(:id => 19, :name => "Mike Huckabee")
Guest.create(:id => 20, :name => "Ken Burns")
Guest.create(:id => 21, :name => "Martha Plimpton")
Guest.create(:id => 22, :name => "Jeff Wild")
Guest.create(:id => 23, :name => "Jen Kirkman")
Guest.create(:id => 24, :name => "Ryan Stout")
Guest.create(:id => 25, :name => "guest host Ross Mathews")
Guest.create(:id => 26, :name => "Bryan Cranston")
Guest.create(:id => 27, :name => "the Ringling Bros. \"Globe of Steel\"")
Guest.create(:id => 28, :name => "Walk the Moon")
Guest.create(:id => 29, :name => "Newt & Callista Gingrich")
Guest.create(:id => 30, :name => "Jake Tapper")
Guest.create(:id => 31, :name => "Lisa Ling")
Guest.create(:id => 32, :name => "Donnie Wahlberg")
Guest.create(:id => 33, :name => "Katherine Kallinis Berman & Sophie Kallinis LaMontagne")
Guest.create(:id => 34, :name => "Robert DeNiro")
Guest.create(:id => 35, :name => "Isla Fisher")
Guest.create(:id => 36, :name => "Connor Cruise")
Guest.create(:id => 37, :name => "Adam Levine")
Guest.create(:id => 38, :name => "Jennifer Hudson")
Guest.create(:id => 39, :name => "Maroon 5")
Guest.create(:id => 40, :name => "Judge Judy Sheindlin")
Guest.create(:id => 41, :name => "Julianna Margulies")
Guest.create(:id => 42, :name => "Stupid Pet Tricks")
Guest.create(:id => 43, :name => "Mumford & Sons")
Guest.create(:id => 44, :name => "Keira Knightley")
Guest.create(:id => 45, :name => "Whitney Cummings")
Guest.create(:id => 46, :name => "Gin Wigmore")
Guest.create(:id => 47, :name => "Christina Applegate")
Guest.create(:id => 48, :name => "\"Dancing with the Stars\" castoffs Kirstie Alley & Gilles Marini")
Guest.create(:id => 49, :name => "Youngblood Hawk")
Guest.create(:id => 50, :name => "J.R. Martinez")
Guest.create(:id => 51, :name => "Sally Field")
Guest.create(:id => 52, :name => "Finesse Mitchell")
Guest.create(:id => 53, :name => "Elon Musk")
Guest.create(:id => 54, :name => "Lee Brice")
Guest.create(:id => 55, :name => "Keegan-Michael Key & Jordan Peele")
Guest.create(:id => 56, :name => "Buffalo Girls")
Guest.create(:id => 57, :name => "Ceremony")
Guest.create(:id => 58, :name => "Frank Rich")
Guest.create(:id => 59, :name => "Jason Sudeikis")
Guest.create(:id => 60, :name => "Newt Gingrich")
Guest.create(:id => 61, :name => "Greg Fitzsimmons")
Guest.create(:id => 62, :name => "Loni Love")
Guest.create(:id => 63, :name => "Matt Braunger")
Guest.create(:id => 64, :name => "Joel McHale")
Guest.create(:id => 65, :name => "James \"Bobo\" Fay")
Guest.create(:id => 66, :name => "Just Sayin' stand-up contest winner Samuel Comroe")
Guest.create(:id => 67, :name => "Rachael Ray & John Cusimano")
Guest.create(:id => 68, :name => "Carrie Fisher")
Guest.create(:id => 69, :name => "Jamie Krell")
Guest.create(:id => 70, :name => "Jason Cameron")
Guest.create(:id => 71, :name => "Andrew Garfield")
Guest.create(:id => 72, :name => "Alison Eastwood & Donald Schultz")
Guest.create(:id => 73, :name => "Ne-Yo")
Guest.create(:id => 74, :name => "Michael Morton")
Guest.create(:id => 75, :name => "Alec Baldwin")
Guest.create(:id => 76, :name => "Dirty Projectors")
Guest.create(:id => 77, :name => "Helen Hunt")
Guest.create(:id => 78, :name => "Paul \"DJ Pauly D\" DelVecchio")
Guest.create(:id => 79, :name => "Kylie Minogue")
Guest.create(:id => 80, :name => "Martin Short")
Guest.create(:id => 81, :name => "Suraj Sharma")
Guest.create(:id => 82, :name => "Billy Crystal")
Guest.create(:id => 83, :name => "Berenice Marlohe")
Guest.create(:id => 84, :name => "Chris Tucker")
Guest.create(:id => 85, :name => "Kellan Lutz")
Guest.create(:id => 86, :name => "Jonathan Becker")
Guest.create(:id => 87, :name => "Electric Guest")
Guest.create(:id => 88, :name => "Robert Greene")
Guest.create(:id => 89, :name => "Witness")
Guest.create(:id => 90, :name => "Divine Fits")
Guest.create(:id => 91, :name => "Jon Meacham")
Guest.create(:id => 92, :name => "Tony Kushner")
Guest.create(:id => 93, :name => "Nate Berkus")
Guest.create(:id => 94, :name => "Kurt Braunohler")
Guest.create(:id => 95, :name => "John Caparulo")
Guest.create(:id => 96, :name => "Annie Lederman")
Guest.create(:id => 97, :name => "Kristen Stewart")
Guest.create(:id => 98, :name => "Glenn Howerton")
Guest.create(:id => 99, :name => "Lianne La Havas")
Guest.create(:id => 100, :name => "James Spader")
Guest.create(:id => 101, :name => "Keri Glassman")
Guest.create(:id => 102, :name => "the Backstreet Boys")
Guest.create(:id => 103, :name => "Hayden Panetierre")
Guest.create(:id => 104, :name => "Rihanna")
Guest.create(:id => 105, :name => "Blue Man Group")
Guest.create(:id => 106, :name => "Dr. Sanjay Gupta")
Guest.create(:id => 107, :name => "Susannah Cahalan")
Guest.create(:id => 108, :name => "Zooey Deschanel")
Guest.create(:id => 109, :name => "Lisa Lampanelli")
Guest.create(:id => 110, :name => "Donald Fagen")
Guest.create(:id => 111, :name => "Tim Allen")
Guest.create(:id => 112, :name => "Nolan Gould")
Guest.create(:id => 113, :name => "Switchfoot")
Guest.create(:id => 114, :name => "Mel Brooks")
Guest.create(:id => 115, :name => "Jason Aldean")
Guest.create(:id => 116, :name => "Max Greenfield")
Guest.create(:id => 117, :name => "Lucy Punch")
Guest.create(:id => 118, :name => "Katie Holmes")
Guest.create(:id => 119, :name => "Jeff Bezos")
Guest.create(:id => 120, :name => "Russell Peters")
Guest.create(:id => 121, :name => "Naomie Harris")
Guest.create(:id => 122, :name => "Dino Stamatopolous")
Guest.create(:id => 123, :name => "Brandi Carlile")
Guest.create(:id => 124, :name => "Andrew Napolitano")
Guest.create(:id => 125, :name => "Chris Stringer")
Guest.create(:id => 126, :name => "Ben Gleib")
Guest.create(:id => 127, :name => "Bobby Lee")
Guest.create(:id => 128, :name => "Marc Maron")
Guest.create(:id => 129, :name => "Jimmy Pardo")
Guest.create(:id => 130, :name => "Jeff the Brotherhood")
Guest.create(:id => 131, :name => "Dr. Phil McGraw")
Guest.create(:id => 132, :name => "Chandra Wilson")
Guest.create(:id => 133, :name => "Jason Latimer")
Guest.create(:id => 134, :name => "Janice Min")
Guest.create(:id => 135, :name => "Ashley Greene")
Guest.create(:id => 136, :name => "Bridgit Mendler")
Guest.create(:id => 137, :name => "One Direction")
Guest.create(:id => 138, :name => "John Edward")
Guest.create(:id => 139, :name => "Char Margolis")
Guest.create(:id => 140, :name => "Randall Sullivan")
Guest.create(:id => 141, :name => "Chris Matthews")
Guest.create(:id => 142, :name => "the Mowgli's")
Guest.create(:id => 143, :name => "David Letterman")
Guest.create(:id => 144, :name => "Vampire Weekend")
Guest.create(:id => 145, :name => "Cynthia Littleton")
Guest.create(:id => 146, :name => "Helen Mirren")
Guest.create(:id => 147, :name => "Carson Daly")
Guest.create(:id => 148, :name => "Reggie Fils-Aime")
Guest.create(:id => 149, :name => "Miguel")
Guest.create(:id => 150, :name => "Chris Elliott")
Guest.create(:id => 151, :name => "\"The Goon\"")
Guest.create(:id => 152, :name => "the Jezabels")
Guest.create(:id => 153, :name => "Hayden Panettiere")
Guest.create(:id => 154, :name => "Brad Wollack")
Guest.create(:id => 155, :name => "Ingrid Haas")
Guest.create(:id => 156, :name => "Ross Mathews")
Guest.create(:id => 157, :name => "Oliver Stone")
Guest.create(:id => 158, :name => "Susan Boyle")
Guest.create(:id => 159, :name => "guest co-host Jay Mohr")
Guest.create(:id => 160, :name => "Rob Reiner")
Guest.create(:id => 161, :name => "Kat Cole")
Guest.create(:id => 162, :name => "Chi-Lan Lieu")
Guest.create(:id => 163, :name => "Jason Cameron & Tony Siragusa")
Guest.create(:id => 164, :name => "Vanessa Williams")
Guest.create(:id => 165, :name => "Jessica Biel")
Guest.create(:id => 166, :name => "Pete Townshend")
Guest.create(:id => 167, :name => "Philip Phillips")
Guest.create(:id => 168, :name => "Jennifer Lawrence")
Guest.create(:id => 169, :name => "Phil & Willie Robertson")
Guest.create(:id => 170, :name => "Andy Grammer")
Guest.create(:id => 171, :name => "Eric Stonestreet")
Guest.create(:id => 172, :name => "L.A. Reid")
Guest.create(:id => 173, :name => "Aimee Mann & James Mercer")
Guest.create(:id => 174, :name => "Regis Philbin")
Guest.create(:id => 175, :name => "Katie Aselton")
Guest.create(:id => 176, :name => "Tony Bennett")
Guest.create(:id => 177, :name => "Zac Brown Band")
Guest.create(:id => 178, :name => "Rerun TBA")
Guest.create(:id => 179, :name => "Rascal Flatts")
Guest.create(:id => 180, :name => "Mo Mandel")
Guest.create(:id => 181, :name => "Natasha Leggero")
Guest.create(:id => 182, :name => "T.J. Miller")
Guest.create(:id => 183, :name => "Kate Beckinsale")
Guest.create(:id => 184, :name => "Doug Fine")
Guest.create(:id => 185, :name => "Tennis")
Guest.create(:id => 186, :name => "Dave Salmoni")
Guest.create(:id => 187, :name => "Alyson Hannigan")
Guest.create(:id => 188, :name => "Lauren Scruggs")
Guest.create(:id => 189, :name => "Thalia")
Guest.create(:id => 190, :name => "Amy Poehler")
Guest.create(:id => 191, :name => "Josh Hutcherson")
Guest.create(:id => 192, :name => "Tegan and Sara")
Guest.create(:id => 193, :name => "Lindsay Lohan")
Guest.create(:id => 194, :name => "David Gregory")
Guest.create(:id => 195, :name => "Wanda Jackson")
Guest.create(:id => 196, :name => "Simon Cowell")
Guest.create(:id => 197, :name => "Demi Lovato")
Guest.create(:id => 198, :name => "the latest \"Dancing with the Stars\" castoff")
Guest.create(:id => 199, :name => "Marion Cotillard")
Guest.create(:id => 200, :name => "Kevin Pollack")
Guest.create(:id => 201, :name => "Al Michaels")
Guest.create(:id => 202, :name => "Miranda Cosgrove")
Guest.create(:id => 203, :name => "Pitbull")
Guest.create(:id => 204, :name => "James Davis")
Guest.create(:id => 205, :name => "Kerri Kenney-Silver")
Guest.create(:id => 206, :name => "Ben Stiller")
Guest.create(:id => 207, :name => "Olivia Munn")
Guest.create(:id => 208, :name => "Flo Rida")
Guest.create(:id => 209, :name => "Rico Rodriguez")
Guest.create(:id => 210, :name => "Jesse Tyler Ferguson")
Guest.create(:id => 211, :name => "Kelly Clarkson")
Guest.create(:id => 212, :name => "TBA")
Guest.create(:id => 213, :name => "Scarlett Johansson")
Guest.create(:id => 214, :name => "Willie Nelson")
Guest.create(:id => 215, :name => "Gary Clark Jr.")
Guest.create(:id => 216, :name => "Joseph Gordon-Levitt")
Guest.create(:id => 217, :name => "Kris Jenner")
Guest.create(:id => 218, :name => "Dan Cummings")
Guest.create(:id => 219, :name => "Manny Pacquiao")
Guest.create(:id => 220, :name => "Tom Hanks")
Guest.create(:id => 221, :name => "Phil Hanley")
Guest.create(:id => 222, :name => "Alicia Keys")
Guest.create(:id => 223, :name => "Chris Franjola")
Guest.create(:id => 224, :name => "Sarah Colonna")
Guest.create(:id => 225, :name => "Dov Davidoff")
Guest.create(:id => 226, :name => "Will Ferrell")
Guest.create(:id => 227, :name => "Tenacious D")
Guest.create(:id => 228, :name => "Nicki Minaj")
Guest.create(:id => 229, :name => "Ina Garten")
Guest.create(:id => 230, :name => "PSY")
Guest.create(:id => 231, :name => "Daniel Craig")
Guest.create(:id => 232, :name => "Stephenie Meyer")
Guest.create(:id => 233, :name => "Boys Like Girls")
Guest.create(:id => 234, :name => "Jay Leno")
Guest.create(:id => 235, :name => "Lynyrd Skynyrd")
Guest.create(:id => 236, :name => "Pre-empted")
Guest.create(:id => 237, :name => "Russell Brand")
Guest.create(:id => 238, :name => "Big K.R.I.T.")
Guest.create(:id => 239, :name => "Sara Ramirez")
Guest.create(:id => 240, :name => "Lana Parrilla")
Guest.create(:id => 241, :name => "Kate Gosselin")
Guest.create(:id => 242, :name => "Abby Lee Miller")
Guest.create(:id => 243, :name => "the cast of \"Gold Rush\"")
Guest.create(:id => 244, :name => "Robert Pattinson")
Guest.create(:id => 245, :name => "Chris Hardwick")
Guest.create(:id => 246, :name => "Ben Folds Five")
Guest.create(:id => 247, :name => "Sarah Shahi")
Guest.create(:id => 248, :name => "Ginnifer Goodwin")
Guest.create(:id => 249, :name => "Michael Yo")
Guest.create(:id => 250, :name => "Heather McDonald")
Guest.create(:id => 251, :name => "Josh Wolf")
Guest.create(:id => 252, :name => "Jack Black")
Guest.create(:id => 253, :name => "Carrot Top")
Guest.create(:id => 254, :name => "Lori Bergamotto")
Guest.create(:id => 255, :name => "Taylor Swift")
Guest.create(:id => 256, :name => "Dolly Parton")
Guest.create(:id => 257, :name => "Bryan Adams")
Guest.create(:id => 258, :name => "Carley Roney")
Guest.create(:id => 259, :name => "Barbra Streisand")
Guest.create(:id => 260, :name => "Frank Oz")
Guest.create(:id => 261, :name => "Kevin McKidd")
Guest.create(:id => 262, :name => "Chris Byrne")
Guest.create(:id => 263, :name => "Magic Johnson")
Guest.create(:id => 264, :name => "Kathy Ireland")
Guest.create(:id => 265, :name => "Sean Carroll")
Guest.create(:id => 266, :name => "Patricia Heaton")
Guest.create(:id => 267, :name => "Clint Carter")
Guest.create(:id => 268, :name => "Rod Stewart")
Guest.create(:id => 269, :name => "Tracy Morgan")
Guest.create(:id => 270, :name => "David Pogue")
