TvShow.create(:id => 1, :name => "Late Show with David Letterman", :identifier => "david letterman")
TvShow.create(:id => 2, :name => "The Tonight Show with Jay Leno", :identifier => "jay leno")
TvShow.create(:id => 3, :name => "Jimmy Kimmel Live", :identifier => "jimmy kimmel")
TvShow.create(:id => 4, :name => "The Late Show with Craig Ferguson", :identifier => "craig ferguson")
TvShow.create(:id => 5, :name => "Late Night with Jimmy Fallon", :identifier => "jimmy fallon")
TvShow.create(:id => 6, :name => "Last Call with Carson Daly", :identifier => "carson daly")
TvShow.create(:id => 7, :name => "Tavis Smiley", :identifier => "tavis smiley")
TvShow.create(:id => 8, :name => "The Daily Show with Jon Stewart", :identifier => "daily show")
TvShow.create(:id => 9, :name => "The Colbert Report", :identifier => "colbert report")
TvShow.create(:id => 10, :name => "Chelsea Lately", :identifier => "chelsea lately")
TvShow.create(:id => 11, :name => "Conan", :identifier => "conan o'brien")
TvShow.create(:id => 12, :name => "The View", :identifier => "the view")
TvShow.create(:id => 13, :name => "The Talk", :identifier => "the talk")
TvShow.create(:id => 14, :name => "Live Kelly & Michael", :identifier => "kelly & michael")
TvShow.create(:id => 15, :name => "The Ellen Degeneres Show", :identifier => "ellen degeneres")
TvShow.create(:id => 16, :name => "Katie Couric Show", :identifier => "katie couric")
